/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */

export interface LoginRequest {
  /** Email address of user */
  email: string;
  /** Password for the account */
  password: string;
}
