/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */

/**
 * Billing period selected for the subscription
 */
export type PaymentDetailsResponseBillingPeriod = typeof PaymentDetailsResponseBillingPeriod[keyof typeof PaymentDetailsResponseBillingPeriod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentDetailsResponseBillingPeriod = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
