/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */
import type { PaymentHistoryResponseProvider } from './paymentHistoryResponseProvider';
import type { PaymentHistoryResponseStatus } from './paymentHistoryResponseStatus';

export interface PaymentHistoryResponse {
  /** Id transaction */
  id: string;
  /** Transaction created at */
  createdAt: string;
  /** Subscription plan name */
  plan: string;
  /** Amount of the transaction */
  amount: number;
  /** Payment provider used for the transaction */
  provider: PaymentHistoryResponseProvider;
  /** Transaction status */
  status: PaymentHistoryResponseStatus;
}
