/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */
import type { PaymentDetailsResponseBillingPeriod } from './paymentDetailsResponseBillingPeriod';
import type { SubscriptionInfo } from './subscriptionInfo';

export interface PaymentDetailsResponse {
  /** Unique identifier of the transaction */
  id: string;
  /** Billing period selected for the subscription */
  billingPeriod: PaymentDetailsResponseBillingPeriod;
  /** Subscription information including selected plan details */
  subscription: SubscriptionInfo;
}
