/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */

export interface PlanInfo {
  /** Unique identifier of the subscription plan */
  id: string;
  /** Subscription plan name */
  title: string;
  /** Monthly price */
  monthlyPrice: number;
  /** Yearly price */
  yearlyPrice: number;
}
