/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */
import type { SubscriptionResponseStatus } from './subscriptionResponseStatus';
import type { PlanResponse } from './planResponse';

export interface SubscriptionResponse {
  /** Current subscription status */
  status: SubscriptionResponseStatus;
  /** Subscription start date */
  startDate: string;
  /** Subscription end date */
  endDate: string;
  plan: PlanResponse;
}
