/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Payment API
 * OpenAPI spec version: 1.4.8.8
 */

export interface UpdateAutoRenewalResponse {
  /** Enable or disable auto-renewal */
  isAutoRenewal: boolean;
}
